version: "3.4"

services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '8080:80'
    container_name: reverse-proxy
    depends_on:
      - app
      - api

  app:
    image: login-client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/:/usr/src/app
    ports:
      - '3000:3000'
    container_name: login-client
    env_file:
      - ./client/.env
    depends_on:
      - api

  api:
    image: login-api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: 'no'
    volumes:
      - ./api/:/usr/src/app
    ports:
      - '7777:7777'
    env_file:
      - ./api/.env
    container_name: login-api